Repository learning-management-system-ci/lms-beecons, pull requests merged in 2022-10, with the labels that each got.

#107 small fixed from 1.1
  app/Views/layouts/app_layout.php
  app/Views/pages/course/course-detail.php
  public/image/course-detail/button-quiz-dark.png
  public/image/course-detail/button-quiz-light.png
  public/image/course-detail/finish.png
  public/image/course-detail/pause-button.png
  public/image/course-detail/person.jpg
  public/image/course-detail/person.png
  public/image/course-detail/play-dark.png
  public/js/home/course-detail.js
  public/style/course-detail.css
  public/style/course-detail.css.map
  public/style/course-detail.scss
Labels: documentation, enhancement

#140 Fe/integration detail course
  app/Config/Routes.php
  app/Controllers/Home.php
  app/Views/pages/course/course-detail.php
  public/js/home/course-detail.js
  public/style/course-detail.css
  public/style/course-detail.css.map
  public/style/course-detail.scss
Labels: hacktoberfest-accepted

#139 cart integration and fixing notification integration
  app/Views/components/home/navbar.php
  app/Views/layouts/app_layout.php
  app/Views/pages/course/cart.php
  app/Views/pages/navigation/courses.php
  public/js/home/cart.js
  public/js/home/courses.js
  public/js/home/home.js
  public/js/home/homepage.js
  public/js/home/notification.js
  public/style/_base.scss
  public/style/cart.css
  public/style/cart.css.map
  public/style/cart.scss
  public/style/courses.css
  public/style/courses.css.map
  public/style/courses.scss
Labels: hacktoberfest-accepted

#143 Delete course tags in home page and add redirect to course checkout
  app/Views/components/home/choose_course.php
  public/js/home/courses.js
  public/js/home/homepage.js
Labels: hacktoberfest-accepted

#145 add email template, minor fix in course detail page
  app/Config/Routes.php
  app/Controllers/Home.php
  app/Views/pages/course/course-detail.php
  public/html_email/email_verify.html
  public/html_email/invoice_info.html
  public/html_email/otp_request.html
  public/html_email/payment_success.html
  public/image/email/Logo.png
  public/image/email/Logo_bnw.png
  public/image/email/dummy_order.png
  public/style/course-detail.css
  public/style/course-detail.css.map
  public/style/course-detail.scss
  public/style/email.css
  public/style/email.css.map
  public/style/email.scss
Labels: enhancement

#161 fixing navigation bar, readjusting container padding, and restyling html email layout
  app/Views/layouts/app_layout.php
  app/Views/pages/course/bundling.php
  app/Views/pages/course/cart.php
  app/Views/pages/course/checkout.php
  app/Views/pages/navigation/terms_and_condition.php
  app/Views/pages/navigation/training.php
  app/Views/pages/navigation/webinar.php
  public/html_email/email_verify.html
  public/html_email/invoice_info.html
  public/html_email/otp_request.html
  public/html_email/payment_success.html
  public/image/email/Logo.png
  public/image/email/Logo_bnw.png
  public/style/app_layout.css
  public/style/app_layout.css.map
  public/style/app_layout.scss
  public/style/bundling.css
  public/style/bundling.css.map
  public/style/bundling.scss
  public/style/checkout.css
  public/style/checkout.css.map
  public/style/checkout.scss
  public/style/webinar-training.css
  public/style/webinar-training.scss
Labels: enhancement
